name: Try log Secrets

on:
  workflow_dispatch:

jobs:
  logs:
    runs-on: ubuntu-latest

    steps:
      - name: Log the secret
        run: |
          for secret in ${{ secrets }}
          do
            echo "$secret"
          done
