name: Update documention
on:
  pull_request:
    branches:
      - main
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: process documentation on server
        uses: Theneo-Inc/api-documentation@1.0.1
        with:
          PATH: test.action/1.yaml
          PROJECT_KEY: Same
          SECRET: c0ceeda4-dc7c-4fd2-a1d4-cf0b7956e333
