name: Update documention
on:
  pull_request:
    branches:
      - main
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: process documentation on server
        uses: theneoAPIDoc/api-documentation@main
        with:
          PATH: 1.yaml
          PROJECT_KEY: ragaca
          SECRET: 60da213f-1c9d-43f2-8f89-aaff97c2390e
